

# IMPORT DATA

InitialData = read.csv(  file = './DataInput/InitialValueInput.csv',sep =',',row.names = 1,
						header = T, fileEncoding="UTF-8-BOM")


ParameterData = read.csv(  file = './DataInput/ParameterInput.csv',sep =',',row.names = 1,
						header = T, fileEncoding="UTF-8-BOM",)


InitCO2Concentration = InitialData['CO2Conc','value']
InitTemp = InitialData['GlobalTemp','value']

################# STOCK DATA #################

InitValue = c( 
  # Economic Stocks (Regional)
		Capital_Low = InitialData['Capital_Low','value'],
		Capital_Mid = InitialData['Capital_Mid','value'],
		Capital_High = InitialData['Capital_High','value'],

  # Resource Stocks (Global)		
		RenewableResources = InitialData['RenewableResources','value'],
		NonrenewableResources = InitialData['NonrenewableResources','value'],

  # Climate Stocks (Global)
		CO2Conc = InitCO2Concentration,
		GlobalTemp = InitTemp,

  # Food Stocks (Global)
		Fisheries = InitialData['Fisheries','value'],  
		Fishstock = InitialData['Fishstock','value'],   
		Livestock = InitialData['Livestock','value'],        
		Crops = InitialData['Crops','value'],
		FoodDemandPC_Low = InitialData['FoodDemandPC_Low','value'],
		FoodDemandPC_Mid = InitialData['FoodDemandPC_Mid','value'],
		FoodDemandPC_High = InitialData['FoodDemandPC_High','value'],
		GrazeLand = InitialData['GrazeLand','value'],
		CropLand = InitialData['CropLand','value'],

  # Health and Education Stocks (Regions)
		EducationServices_Low = InitialData['EducationServices_Low','value'],
		EducationServices_Mid = InitialData['EducationServices_Mid','value'],
		EducationServices_High = InitialData['EducationServices_High','value'],
		HealthServices_Low = InitialData['HealthServices_Low','value'],
		HealthServices_Mid = InitialData['HealthServices_Mid','value'],
        HealthServices_High = InitialData['HealthServices_High','value'],

  # Population Stocks (Regions)        
		Low_RM1 = InitialData['LowPop_RM1','value'],
		Low_RM2 = InitialData['LowPop_RM2','value'],
		Low_RM3 = InitialData['LowPop_RM3','value'],
		Low_RM4 = InitialData['LowPop_RM4','value'],
		Low_RF1 = InitialData['LowPop_RF1','value'],
		Low_RF2 = InitialData['LowPop_RF2','value'],
		Low_RF3 = InitialData['LowPop_RF3','value'],
		Low_RF4 = InitialData['LowPop_RF4','value'],         
		Low_PM1 = InitialData['LowPop_PM1','value'],
		Low_PM2 = InitialData['LowPop_PM2','value'],
		Low_PM3 = InitialData['LowPop_PM3','value'],
		Low_PM4 = InitialData['LowPop_PM4','value'],
		Low_PF1 = InitialData['LowPop_PF1','value'],
		Low_PF2 = InitialData['LowPop_PF2','value'],
		Low_PF3 = InitialData['LowPop_PF3','value'],
		Low_PF4 = InitialData['LowPop_PF4','value'],

		Mid_RM1 = InitialData['MidPop_RM1','value'],
		Mid_RM2 = InitialData['MidPop_RM2','value'],
		Mid_RM3 = InitialData['MidPop_RM3','value'],
		Mid_RM4 = InitialData['MidPop_RM4','value'],
		Mid_RF1 = InitialData['MidPop_RF1','value'],
		Mid_RF2 = InitialData['MidPop_RF2','value'],
		Mid_RF3 = InitialData['MidPop_RF3','value'],
		Mid_RF4 = InitialData['MidPop_RF4','value'],         
		Mid_PM1 = InitialData['MidPop_PM1','value'],
		Mid_PM2 = InitialData['MidPop_PM2','value'],
		Mid_PM3 = InitialData['MidPop_PM3','value'],
		Mid_PM4 = InitialData['MidPop_PM4','value'],
		Mid_PF1 = InitialData['MidPop_PF1','value'],
		Mid_PF2 = InitialData['MidPop_PF2','value'],
		Mid_PF3 = InitialData['MidPop_PF3','value'],
		Mid_PF4 = InitialData['MidPop_PF4','value'],

		High_RM1 = InitialData['HighPop_RM1','value'],
		High_RM2 = InitialData['HighPop_RM2','value'],
		High_RM3 = InitialData['HighPop_RM3','value'],
		High_RM4 = InitialData['HighPop_RM4','value'],
		High_RF1 = InitialData['HighPop_RF1','value'],
		High_RF2 = InitialData['HighPop_RF2','value'],
		High_RF3 = InitialData['HighPop_RF3','value'],
		High_RF4 = InitialData['HighPop_RF4','value'],         
		High_PM1 = InitialData['HighPop_PM1','value'],
		High_PM2 = InitialData['HighPop_PM2','value'],
		High_PM3 = InitialData['HighPop_PM3','value'],
		High_PM4 = InitialData['HighPop_PM4','value'],
		High_PF1 = InitialData['HighPop_PF1','value'],
		High_PF2 = InitialData['HighPop_PF2','value'],
		High_PF3 = InitialData['HighPop_PF3','value'],
		High_PF4 = InitialData['HighPop_PF4','value'],

  # Water Stocks (Global)
		Freshwater = InitialData['Freshwater','value'])


################# PARAMETER DATA #################

ParameterValue = list(
  # Population Coefficients
		MinDeath = ParameterData['MinDeath','value'],
		TNMFR = ParameterData['TNMFR','value'],
		AlphaC = ParameterData['AlphaC','value'],
		BetaEC = ParameterData['BetaEC','value'],
		BetaHC = ParameterData['BetaHC','value'],
		AlphaM = ParameterData['AlphaM','value'],
		BetaEM = ParameterData['BetaEM','value'],
		TotalFecundity = ParameterData['TotalFecundity','value'],
		Beta1 = ParameterData['Beta1','value'],
		FemaleBirthRatio = ParameterData['FemaleBirthRatio','value'],

		OmegaF_M1 = ParameterData['OmegaF_M1','value'],
		OmegaF_M2 = ParameterData['OmegaF_M2','value'],
		OmegaF_M3 = ParameterData['OmegaF_M3','value'],
		OmegaF_M4 = ParameterData['OmegaF_M4','value'],
		OmegaF_F1 = ParameterData['OmegaF_F1','value'],
		OmegaF_F2 = ParameterData['OmegaF_F2','value'],
		OmegaF_F3 = ParameterData['OmegaF_F3','value'],
		OmegaF_F4 = ParameterData['OmegaF_F4','value'],

		OmegaH_M1 = ParameterData['OmegaH_M1','value'],
		OmegaH_M2 = ParameterData['OmegaH_M2','value'],
		OmegaH_M3 = ParameterData['OmegaH_M3','value'],
		OmegaH_M4 = ParameterData['OmegaH_M4','value'],
		OmegaH_F1 = ParameterData['OmegaH_F1','value'],
		OmegaH_F2 = ParameterData['OmegaH_F2','value'],
		OmegaH_F3 = ParameterData['OmegaH_F3','value'],
		OmegaH_F4 = ParameterData['OmegaH_F4','value'],	
		NutritionReq = ParameterData['NutritionReq','value'],

  # Food Coefficients
		ThetaU = ParameterData['ThetaU','value'],
		ZetaU = ParameterData['ZetaU','value'],
		GrazeLandGrowthRate = ParameterData['GrazeLandGrowthRate','value'],
		GrazeLandLossRate = ParameterData['GrazeLandLossRate','value'],
		CropLandGrowthRate = ParameterData['CropLandGrowthRate','value'],
		CropLandLossRate = ParameterData['CropLandLossRate','value'],
		LandProdElastLivestock = ParameterData['LandProdElastLivestock','value'],
		WaterProdElastLivestock = ParameterData['WaterProdElastLivestock','value'],
		LivestockTechMult = ParameterData['LivestockTechMult','value'],
		WaterProdEastCrops = ParameterData['WaterProdEastCrops','value'],
		LandProdElastCrops = ParameterData['LandProdElastCrops','value'],
		CropsTechMult = ParameterData['CropsTechMult','value'],

		FoodNutrConv_Fish = ParameterData['FoodNutrConv_Fish','value'],
		FoodNutrConv_Livestock = ParameterData['FoodNutrConv_Livestock','value'],
		FoodNutrConv_Crops = ParameterData['FoodNutrConv_Crops','value'],
		
		FishConsFrac_Fish = ParameterData['FishConsFrac_Fish','value'],
		FishConsFrac_Livestock = ParameterData['FishConsFrac_Livestock','value'],
		FishConsFrac_Crops = ParameterData['FishConsFrac_Crops','value'],
		FishProdDelay = ParameterData['FishProdDelay','value'],
		
		LivestockProdDelay = ParameterData['LivestockProdDelay','value'],
		CropsProdDelay = ParameterData['CropsProdDelay','value'],
		FoodIncomeElasticity_Low = ParameterData['FoodIncomeElasticity_Low','value'],
		FoodIncomeElasticity_Mid = ParameterData['FoodIncomeElasticity_Mid','value'],
		FoodIncomeElasticity_High = ParameterData['FoodIncomeElasticity_High','value'],
		FoodAccess_RichLow = ParameterData['FoodAccess_RichLow','value'],
		FoodAccess_RichMid = ParameterData['FoodAccess_RichMid','value'],
		FoodAccess_RichHigh = ParameterData['FoodAccess_RichHigh','value'],
		FoodAccess_PoorLow = ParameterData['FoodAccess_PoorLow','value'],
		FoodAccess_PoorMid = ParameterData['FoodAccess_PoorMid','value'],
		FoodAccess_PoorHigh = ParameterData['FoodAccess_PoorHigh','value'],
		FishWasteFrac = ParameterData['FishWasteFrac','value'],
		LivestockWasteFrac = ParameterData['LivestockWasteFrac','value'],
		CropsWasteFrac = ParameterData['CropsWasteFrac','value'],

    # Climate Coefficients
		Lambda = ParameterData['Lambda','value'],
		RefTemp = InitTemp,
		PsiE_Low = ParameterData['PsiE_Low','value'],
		PsiE_Mid = ParameterData['PsiE_Mid','value'],		
		PsiE_High = ParameterData['PsiE_High','value'],
		Gamma = ParameterData['Gamma','value'],
		RefCO2Conc = InitCO2Concentration,
		OtherRadForce = ParameterData['OtherRadForce','value'],

    # Economy Coefficients
		RenewableCapitalReturn_Low = ParameterData['RenewableCapitalReturn_Low','value'],
		RenewableCapitalReturn_Mid = ParameterData['RenewableCapitalReturn_Mid','value'],
		RenewableCapitalReturn_High = ParameterData['RenewableCapitalReturn_High','value'],
		NonrenewableCapitalReturn_Low = ParameterData['NonrenewableCapitalReturn_Low','value'],
		NonrenewableCapitalReturn_Mid = ParameterData['NonrenewableCapitalReturn_Mid','value'],
		NonrenewableCapitalReturn_High = ParameterData['NonrenewableCapitalReturn_High','value'],
		CapitalInputElast_Low = ParameterData['CapitalInputElast_Low','value'],
		CapitalInputElast_Mid = ParameterData['CapitalInputElast_Mid','value'],
		CapitalInputElast_High = ParameterData['CapitalInputElast_High','value'],
		LaborInputElast_Low = ParameterData['LaborInputElast_Low','value'],
		LaborInputElast_Mid = ParameterData['LaborInputElast_Mid','value'],
		LaborInputElast_High = ParameterData['LaborInputElast_High','value'],
		TechMult_Low = ParameterData['TechMult_Low','value'],
		TechMult_Mid = ParameterData['TechMult_Mid','value'],
		TechMult_High = ParameterData['TechMult_High','value'],
		RenewableAccess_Low = ParameterData['RenewableAccess_Low','value'],
		RenewableAccess_Mid = ParameterData['RenewableAccess_Mid','value'],
		RenewableAccess_High = ParameterData['RenewableAccess_High','value'],
		NonrenewableAccess_Low = ParameterData['NonrenewableAccess_Low','value'],
		NonrenewableAccess_Mid = ParameterData['NonrenewableAccess_Mid','value'],
		NonrenewableAccess_High = ParameterData['NonrenewableAccess_High','value'],
		LowEmployedWorkRatio_RM1 = ParameterData['LowEmployedWorkRatio_RM1','value'], 
		LowEmployedWorkRatio_RM2 = ParameterData['LowEmployedWorkRatio_RM2','value'], 
		LowEmployedWorkRatio_RM3 = ParameterData['LowEmployedWorkRatio_RM3','value'], 
		LowEmployedWorkRatio_RM4 = ParameterData['LowEmployedWorkRatio_RM4','value'], 
		LowEmployedWorkRatio_RF1 = ParameterData['LowEmployedWorkRatio_RF1','value'], 
		LowEmployedWorkRatio_RF2 = ParameterData['LowEmployedWorkRatio_RF2','value'], 
		LowEmployedWorkRatio_RF3 = ParameterData['LowEmployedWorkRatio_RF3','value'], 
		LowEmployedWorkRatio_RF4 = ParameterData['LowEmployedWorkRatio_RF4','value'],            
		LowEmployedWorkRatio_PM1 = ParameterData['LowEmployedWorkRatio_PM1','value'], 
		LowEmployedWorkRatio_PM2 = ParameterData['LowEmployedWorkRatio_PM2','value'], 
		LowEmployedWorkRatio_PM3 = ParameterData['LowEmployedWorkRatio_PM3','value'], 
		LowEmployedWorkRatio_PM4 = ParameterData['LowEmployedWorkRatio_PM4','value'], 
		LowEmployedWorkRatio_PF1 = ParameterData['LowEmployedWorkRatio_PF1','value'], 
		LowEmployedWorkRatio_PF2 = ParameterData['LowEmployedWorkRatio_PF2','value'], 
		LowEmployedWorkRatio_PF3 = ParameterData['LowEmployedWorkRatio_PF3','value'], 
		LowEmployedWorkRatio_PF4 = ParameterData['LowEmployedWorkRatio_PF4','value'],

		MidEmployedWorkRatio_RM1 = ParameterData['MidEmployedWorkRatio_RM1','value'], 
		MidEmployedWorkRatio_RM2 = ParameterData['MidEmployedWorkRatio_RM2','value'], 
		MidEmployedWorkRatio_RM3 = ParameterData['MidEmployedWorkRatio_RM3','value'], 
		MidEmployedWorkRatio_RM4 = ParameterData['MidEmployedWorkRatio_RM4','value'], 
		MidEmployedWorkRatio_RF1 = ParameterData['MidEmployedWorkRatio_RF1','value'], 
		MidEmployedWorkRatio_RF2 = ParameterData['MidEmployedWorkRatio_RF2','value'], 
		MidEmployedWorkRatio_RF3 = ParameterData['MidEmployedWorkRatio_RF3','value'], 
		MidEmployedWorkRatio_RF4 = ParameterData['MidEmployedWorkRatio_RF4','value'],            
		MidEmployedWorkRatio_PM1 = ParameterData['MidEmployedWorkRatio_PM1','value'], 
		MidEmployedWorkRatio_PM2 = ParameterData['MidEmployedWorkRatio_PM2','value'], 
		MidEmployedWorkRatio_PM3 = ParameterData['MidEmployedWorkRatio_PM3','value'], 
		MidEmployedWorkRatio_PM4 = ParameterData['MidEmployedWorkRatio_PM4','value'], 
		MidEmployedWorkRatio_PF1 = ParameterData['MidEmployedWorkRatio_PF1','value'], 
		MidEmployedWorkRatio_PF2 = ParameterData['MidEmployedWorkRatio_PF2','value'], 
		MidEmployedWorkRatio_PF3 = ParameterData['MidEmployedWorkRatio_PF3','value'], 
		MidEmployedWorkRatio_PF4 = ParameterData['MidEmployedWorkRatio_PF4','value'],

		HighEmployedWorkRatio_RM1 = ParameterData['HighEmployedWorkRatio_RM1','value'], 
		HighEmployedWorkRatio_RM2 = ParameterData['HighEmployedWorkRatio_RM2','value'], 
		HighEmployedWorkRatio_RM3 = ParameterData['HighEmployedWorkRatio_RM3','value'], 
		HighEmployedWorkRatio_RM4 = ParameterData['HighEmployedWorkRatio_RM4','value'], 
		HighEmployedWorkRatio_RF1 = ParameterData['HighEmployedWorkRatio_RF1','value'], 
		HighEmployedWorkRatio_RF2 = ParameterData['HighEmployedWorkRatio_RF2','value'], 
		HighEmployedWorkRatio_RF3 = ParameterData['HighEmployedWorkRatio_RF3','value'], 
		HighEmployedWorkRatio_RF4 = ParameterData['HighEmployedWorkRatio_RF4','value'],            
		HighEmployedWorkRatio_PM1 = ParameterData['HighEmployedWorkRatio_PM1','value'], 
		HighEmployedWorkRatio_PM2 = ParameterData['HighEmployedWorkRatio_PM2','value'], 
		HighEmployedWorkRatio_PM3 = ParameterData['HighEmployedWorkRatio_PM3','value'], 
		HighEmployedWorkRatio_PM4 = ParameterData['HighEmployedWorkRatio_PM4','value'], 
		HighEmployedWorkRatio_PF1 = ParameterData['HighEmployedWorkRatio_PF1','value'], 
		HighEmployedWorkRatio_PF2 = ParameterData['HighEmployedWorkRatio_PF2','value'], 
		HighEmployedWorkRatio_PF3 = ParameterData['HighEmployedWorkRatio_PF3','value'], 
		HighEmployedWorkRatio_PF4 = ParameterData['HighEmployedWorkRatio_PF4','value'],
		SavingsRate_Low = ParameterData['SavingsRate_Low','value'],
		SavingsRate_Mid = ParameterData['SavingsRate_Mid','value'],
		SavingsRate_High = ParameterData['SavingsRate_High','value'],
		DeprecRate_Low = ParameterData['DeprecRate_Low','value'],
		DeprecRate_Mid = ParameterData['DeprecRate_Mid','value'],
		DeprecRate_High = ParameterData['DeprecRate_High','value'],
		IneqMult_Low = ParameterData['IneqMult_Low','value'],
		IneqMult_Mid = ParameterData['IneqMult_Mid','value'],
		IneqMult_High = ParameterData['IneqMult_High','value'],
		InitEconOutputGrowth_Low = ParameterData['InitEconOutputGrowth_Low','value'],
		InitEconOutputGrowth_Mid = ParameterData['InitEconOutputGrowth_Mid','value'],
		InitEconOutputGrowth_High = ParameterData['InitEconOutputGrowth_High','value'],

	# Resource Coefficients	
		ReplRateRenewable = ParameterData['ReplRateRenewable','value'],
		RenewableConsIntensity_Low = ParameterData['RenewableConsIntensity_Low','value'],
		RenewableConsIntensity_Mid = ParameterData['RenewableConsIntensity_Mid','value'],
		RenewableConsIntensity_High = ParameterData['RenewableConsIntensity_High','value'],
		NonrenewableConsIntensity_Low = ParameterData['NonrenewableConsIntensity_Low','value'],		
		NonrenewableConsIntensity_Mid = ParameterData['NonrenewableConsIntensity_Mid','value'],
		NonrenewableConsIntensity_High = ParameterData['NonrenewableConsIntensity_High','value'],

    # Water Coefficients
		DeltaW = ParameterData['DeltaW','value'],
		WaterReplRate = ParameterData['WaterReplRate','value'],
		ZetaI_Low = ParameterData['ZetaI_Low','value'],
		ZetaI_Mid = ParameterData['ZetaI_Mid','value'],
		ZetaI_High = ParameterData['ZetaI_High','value'],
		WaterDemandPC_Low = ParameterData['WaterDemandPC_Low','value'],
		WaterDemandPC_Mid = ParameterData['WaterDemandPC_Mid','value'],
		WaterDemandPC_High = ParameterData['WaterDemandPC_High','value'],

    # Health and Education Coefficients
		EducationInvestFrac_Low = ParameterData['EducationInvestFrac_Low','value'],
		EducationInvestFrac_Mid = ParameterData['EducationInvestFrac_Mid','value'],
		EducationInvestFrac_High = ParameterData['EducationInvestFrac_High','value'],
		HealthInvestFrac_Low = ParameterData['HealthInvestFrac_Low','value'],
		HealthInvestFrac_Mid = ParameterData['HealthInvestFrac_Mid','value'],
		HealthInvestFrac_High = ParameterData['HealthInvestFrac_High','value'],
		ZetaE_Low = ParameterData['ZetaE_Low','value'],
		ZetaE_Mid = ParameterData['ZetaE_Mid','value'],
		ZetaE_High = ParameterData['ZetaE_High','value'],
		ZetaH_Low = ParameterData['ZetaH_Low','value'],
		ZetaH_Mid = ParameterData['ZetaH_Mid','value'],
		ZetaH_High = ParameterData['ZetaH_High','value'],
		LambdaE_Low = ParameterData['LambdaE_Low','value'],
		LambdaE_Mid = ParameterData['LambdaE_Mid','value'],
		LambdaE_High = ParameterData['LambdaE_High','value'],
		LambdaH_Low = ParameterData['LambdaH_Low','value'],
		LambdaH_Mid = ParameterData['LambdaH_Mid','value'],
		LambdaH_High = ParameterData['LambdaH_High','value'],
		ChiEF1_RichLow = ParameterData['ChiEF1_RichLow','value'],
		ChiEF1_RichMid = ParameterData['ChiEF1_RichMid','value'],
		ChiEF1_RichHigh = ParameterData['ChiEF1_RichHigh','value'], 
		ChiEF1_PoorLow = ParameterData['ChiEF1_PoorLow','value'],
		ChiEF1_PoorMid = ParameterData['ChiEF1_PoorMid','value'],
		ChiEF1_PoorHigh = ParameterData['ChiEF1_PoorHigh','value'],
		ChiHF1_RichLow = ParameterData['ChiHF1_RichLow','value'],
		ChiHF1_RichMid = ParameterData['ChiHF1_RichMid','value'],
		ChiHF1_RichHigh = ParameterData['ChiHF1_RichHigh','value'], 
		ChiHF1_PoorLow = ParameterData['ChiHF1_PoorLow','value'],
		ChiHF1_PoorMid = ParameterData['ChiHF1_PoorMid','value'],
		ChiHF1_PoorHigh = ParameterData['ChiHF1_PoorHigh','value'],
		ChiHA1_RichLow = ParameterData['ChiHA1_RichLow','value'],
		ChiHA1_RichMid = ParameterData['ChiHA1_RichMid','value'],
		ChiHA1_RichHigh = ParameterData['ChiHA1_RichHigh','value'], 
		ChiHA1_PoorLow = ParameterData['ChiHA1_PoorLow','value'],
		ChiHA1_PoorMid = ParameterData['ChiHA1_PoorMid','value'],
		ChiHA1_PoorHigh = ParameterData['ChiHA1_PoorHigh','value'],
		ChiEF2_RichLow = ParameterData['ChiEF2_RichLow','value'],
		ChiEF2_RichMid = ParameterData['ChiEF2_RichMid','value'],
		ChiEF2_RichHigh = ParameterData['ChiEF2_RichHigh','value'], 
		ChiEF2_PoorLow = ParameterData['ChiEF2_PoorLow','value'],
		ChiEF2_PoorMid = ParameterData['ChiEF2_PoorMid','value'],
		ChiEF2_PoorHigh = ParameterData['ChiEF2_PoorHigh','value'],
		ChiHF2_RichLow = ParameterData['ChiHF2_RichLow','value'],
		ChiHF2_RichMid = ParameterData['ChiHF2_RichMid','value'],
		ChiHF2_RichHigh = ParameterData['ChiHF2_RichHigh','value'], 
		ChiHF2_PoorLow = ParameterData['ChiHF2_PoorLow','value'],
		ChiHF2_PoorMid = ParameterData['ChiHF2_PoorMid','value'],
		ChiHF2_PoorHigh = ParameterData['ChiHF2_PoorHigh','value'],
		ChiHA2_RichLow = ParameterData['ChiHA2_RichLow','value'],
		ChiHA2_RichMid = ParameterData['ChiHA2_RichMid','value'],
		ChiHA2_RichHigh = ParameterData['ChiHA2_RichHigh','value'], 
		ChiHA2_PoorLow = ParameterData['ChiHA2_PoorLow','value'],
		ChiHA2_PoorMid = ParameterData['ChiHA2_PoorMid','value'],
		ChiHA2_PoorHigh = ParameterData['ChiHA2_PoorHigh','value'],
		ChiEF3_RichLow = ParameterData['ChiEF3_RichLow','value'],
		ChiEF3_RichMid = ParameterData['ChiEF3_RichMid','value'],
		ChiEF3_RichHigh = ParameterData['ChiEF3_RichHigh','value'], 
		ChiEF3_PoorLow = ParameterData['ChiEF3_PoorLow','value'],
		ChiEF3_PoorMid = ParameterData['ChiEF3_PoorMid','value'],
		ChiEF3_PoorHigh = ParameterData['ChiEF3_PoorHigh','value'],
		ChiHF3_RichLow = ParameterData['ChiHF3_RichLow','value'],
		ChiHF3_RichMid = ParameterData['ChiHF3_RichMid','value'],
		ChiHF3_RichHigh = ParameterData['ChiHF3_RichHigh','value'], 
		ChiHF3_PoorLow = ParameterData['ChiHF3_PoorLow','value'],
		ChiHF3_PoorMid = ParameterData['ChiHF3_PoorMid','value'],
		ChiHF3_PoorHigh = ParameterData['ChiHF3_PoorHigh','value'],
		ChiHA3_RichLow = ParameterData['ChiHA3_RichLow','value'],
		ChiHA3_RichMid = ParameterData['ChiHA3_RichMid','value'],
		ChiHA3_RichHigh = ParameterData['ChiHA3_RichHigh','value'], 
		ChiHA3_PoorLow = ParameterData['ChiHA3_PoorLow','value'],
		ChiHA3_PoorMid = ParameterData['ChiHA3_PoorMid','value'],
		ChiHA3_PoorHigh = ParameterData['ChiHA3_PoorHigh','value'])