library(reshape)


# IMPORT DATA

InitialData = read.csv(  file = './DataInput/InitialValueInput.csv',sep =',',row.names = 1,
						header = T, fileEncoding="UTF-8-BOM")


ParameterData = read.csv(  file = './DataInput/ParameterInput.csv',sep =',',row.names = 1,
						header = T, fileEncoding="UTF-8-BOM")

CalibData = read.csv(  file = './DataInput/CalibrationInput.csv',sep =',',
						header = T, fileEncoding="UTF-8-BOM")



################# STOCK DATA #################

InitValue = c( 
  # Economic Stocks (Regional)
		Capital_Low = InitialData['Capital_Low','value'],
		Capital_Mid = InitialData['Capital_Mid','value'],
		Capital_High = InitialData['Capital_High','value'],

  # Resource Stocks (Global)		
		CoalReserves = InitialData['CoalReserves','value'],
		OilReserves = InitialData['OilReserves','value'],
		GasReserves = InitialData['GasReserves','value'],

  # Climate Stocks (Global)
		CO2Conc = InitialData['CO2Conc','value'],

  # Food Stocks (Global)
		Fisheries = InitialData['Fisheries','value'],  
		Fishstock = InitialData['Fishstock','value'],   
		Livestock = InitialData['Livestock','value'],        
		Crops = InitialData['Crops','value'],
		FoodDemandPC_Low = InitialData['FoodDemandPC_Low','value'],
		FoodDemandPC_Mid = InitialData['FoodDemandPC_Mid','value'],
		FoodDemandPC_High = InitialData['FoodDemandPC_High','value'],
		GrazeLand = InitialData['GrazeLand','value'],
		CropLand = InitialData['CropLand','value'],

  # Health and Education Stocks (Regions)
		EducationServices_Low = InitialData['EducationServices_Low','value'],
		EducationServices_Mid = InitialData['EducationServices_Mid','value'],
		EducationServices_High = InitialData['EducationServices_High','value'],
		HealthServices_Low = InitialData['HealthServices_Low','value'],
		HealthServices_Mid = InitialData['HealthServices_Mid','value'],
        HealthServices_High = InitialData['HealthServices_High','value'],

  # Population Stocks (Regions)        
		Low_M1 = InitialData['LowPop_M1','value'],
		Low_M2 = InitialData['LowPop_M2','value'],
		Low_M3 = InitialData['LowPop_M3','value'],
		Low_M4 = InitialData['LowPop_M4','value'],
		Low_F1 = InitialData['LowPop_F1','value'],
		Low_F2 = InitialData['LowPop_F2','value'],
		Low_F3 = InitialData['LowPop_F3','value'],
		Low_F4 = InitialData['LowPop_F4','value'],
		Mid_M1 = InitialData['MidPop_M1','value'],
		Mid_M2 = InitialData['MidPop_M2','value'],
		Mid_M3 = InitialData['MidPop_M3','value'],
		Mid_M4 = InitialData['MidPop_M4','value'],
		Mid_F1 = InitialData['MidPop_F1','value'],
		Mid_F2 = InitialData['MidPop_F2','value'],
		Mid_F3 = InitialData['MidPop_F3','value'],
		Mid_F4 = InitialData['MidPop_F4','value'],      
		High_M1 = InitialData['HighPop_M1','value'],
		High_M2 = InitialData['HighPop_M2','value'],
		High_M3 = InitialData['HighPop_M3','value'],
		High_M4 = InitialData['HighPop_M4','value'],
		High_F1 = InitialData['HighPop_F1','value'],
		High_F2 = InitialData['HighPop_F2','value'],
		High_F3 = InitialData['HighPop_F3','value'],
		High_F4 = InitialData['HighPop_F4','value'],         

  # Water Stocks (Global)
		Freshwater = InitialData['Freshwater','value'])


################# PARAMETER DATA #################

ParameterValue = list(
  # Population Coefficients
		MinDeath_RichM1 = ParameterData['MinDeath_RichM1','value'],
		MinDeath_PoorM1 = ParameterData['MinDeath_PoorM1','value'],
		MinDeath_M2 = ParameterData['MinDeath_M2','value'],
        MinDeath_M3 = ParameterData['MinDeath_M3','value'],
		MinDeath_M4 = ParameterData['MinDeath_M4','value'],
		MinDeath_RichF1 = ParameterData['MinDeath_RichF1','value'],
		MinDeath_PoorF1 = ParameterData['MinDeath_PoorF1','value'],
		MinDeath_F2 = ParameterData['MinDeath_F2','value'],
        MinDeath_F3 = ParameterData['MinDeath_F3','value'],
        MinDeath_F4 = ParameterData['MinDeath_F4','value'],
		OmegaF_RichM1 = ParameterData['OmegaF_RichM1','value'],
		OmegaF_PoorM1 = ParameterData['OmegaF_PoorM1','value'],
		OmegaF_M2 = ParameterData['OmegaF_M2','value'],
		OmegaF_M3 = ParameterData['OmegaF_M3','value'],
		OmegaF_M4 = ParameterData['OmegaF_M4','value'],
		OmegaF_RichF1 = ParameterData['OmegaF_RichF1','value'],
		OmegaF_PoorF1 = ParameterData['OmegaF_PoorF1','value'],		
		OmegaF_F2 = ParameterData['OmegaF_F2','value'],
		OmegaF_F3 = ParameterData['OmegaF_F3','value'],
		OmegaF_F4 = ParameterData['OmegaF_F4','value'],

		OmegaH_RichM1 = ParameterData['OmegaH_RichM1','value'],
		OmegaH_PoorM1 = ParameterData['OmegaH_PoorM1','value'],
		OmegaH_M2 = ParameterData['OmegaH_M2','value'],
		OmegaH_M3 = ParameterData['OmegaH_M3','value'],
		OmegaH_M4 = ParameterData['OmegaH_M4','value'],
		OmegaH_RichF1 = ParameterData['OmegaH_RichF1','value'],
		OmegaH_PoorF1 = ParameterData['OmegaH_PoorF1','value'],
		OmegaH_F2 = ParameterData['OmegaH_F2','value'],
		OmegaH_F3 = ParameterData['OmegaH_F3','value'],
		OmegaH_F4 = ParameterData['OmegaH_F4','value'],	

		AlphaGFR = ParameterData['AlphaGFR','value'],
		BetaE = ParameterData['BetaE','value'],
		BetaH = ParameterData['BetaH','value'],

		FemaleBirthRatio = ParameterData['FemaleBirthRatio','value'],
		NutritionReq = ParameterData['NutritionReq','value'],
		PoorFrac = ParameterData['PoorFrac','value'],

  # Food Coefficients
		ThetaU = ParameterData['ThetaU','value'],
		ZetaU = ParameterData['ZetaU','value'],
		GrazeLandGrowthRate = ParameterData['GrazeLandGrowthRate','value'],
		GrazeLandLossRate = ParameterData['GrazeLandLossRate','value'],
		CropLandGrowthRate = ParameterData['CropLandGrowthRate','value'],
		CropLandLossRate = ParameterData['CropLandLossRate','value'],
		LandProdElastLivestock = ParameterData['LandProdElastLivestock','value'],
		WaterProdElastLivestock = ParameterData['WaterProdElastLivestock','value'],
		LivestockTechMult = ParameterData['LivestockTechMult','value'],
		WaterProdEastCrops = ParameterData['WaterProdEastCrops','value'],
		LandProdElastCrops = ParameterData['LandProdElastCrops','value'],
		CropsTechMult = ParameterData['CropsTechMult','value'],

		FoodNutrConvMultiplier = ParameterData['FoodNutrConvMultiplier','value'],
		FoodNutrConv_Fish = ParameterData['FoodNutrConv_Fish','value'],
		FoodNutrConv_Livestock = ParameterData['FoodNutrConv_Livestock','value'],
		FoodNutrConv_Crops = ParameterData['FoodNutrConv_Crops','value'],
		
		FoodConsFrac_Fish = ParameterData['FoodConsFrac_Fish','value'],
		FoodConsFrac_Livestock = ParameterData['FoodConsFrac_Livestock','value'],
		FoodConsFrac_Crops = ParameterData['FoodConsFrac_Crops','value'],
		
		FishProdDelay = ParameterData['FishProdDelay','value'],
		LivestockProdDelay = ParameterData['LivestockProdDelay','value'],
		CropsProdDelay = ParameterData['CropsProdDelay','value'],
		FoodIncomeElasticity_Low = ParameterData['FoodIncomeElasticity_Low','value'],
		FoodIncomeElasticity_Mid = ParameterData['FoodIncomeElasticity_Mid','value'],
		FoodIncomeElasticity_High = ParameterData['FoodIncomeElasticity_High','value'],
		FishAccess_RichLow = ParameterData['FishAccess_RichLow','value'],
		FishAccess_RichMid = ParameterData['FishAccess_RichMid','value'],
		FishAccess_RichHigh = ParameterData['FishAccess_RichHigh','value'],
		FishAccess_PoorLow = ParameterData['FishAccess_PoorLow','value'],
		FishAccess_PoorMid = ParameterData['FishAccess_PoorMid','value'],
		FishAccess_PoorHigh = ParameterData['FishAccess_PoorHigh','value'],
		LivestockAccess_RichLow = ParameterData['LivestockAccess_RichLow','value'],
		LivestockAccess_RichMid = ParameterData['LivestockAccess_RichMid','value'],
		LivestockAccess_RichHigh = ParameterData['LivestockAccess_RichHigh','value'],
		LivestockAccess_PoorLow = ParameterData['LivestockAccess_PoorLow','value'],
		LivestockAccess_PoorMid = ParameterData['LivestockAccess_PoorMid','value'],
		LivestockAccess_PoorHigh = ParameterData['LivestockAccess_PoorHigh','value'],
		CropsAccess_RichLow = ParameterData['CropsAccess_RichLow','value'],
		CropsAccess_RichMid = ParameterData['CropsAccess_RichMid','value'],
		CropsAccess_RichHigh = ParameterData['CropsAccess_RichHigh','value'],
		CropsAccess_PoorLow = ParameterData['CropsAccess_PoorLow','value'],
		CropsAccess_PoorMid = ParameterData['CropsAccess_PoorMid','value'],
		CropsAccess_PoorHigh = ParameterData['CropsAccess_PoorHigh','value'],
		FishWasteFrac = ParameterData['FishWasteFrac','value'],
		LivestockWasteFrac = ParameterData['LivestockWasteFrac','value'],
		CropsWasteFrac = ParameterData['CropsWasteFrac','value'],
		WaterCropFrac = ParameterData['WaterCropFrac','value'],
		MinFoodProd = ParameterData['MinFoodProd','value'],

    # Climate Coefficients
		Lambda = ParameterData['Lambda','value'],
		PsiE1_Low = ParameterData['PsiE1_Low','value'],
		PsiE1_Mid = ParameterData['PsiE1_Mid','value'],		
		PsiE1_High = ParameterData['PsiE1_High','value'],
		PsiE2_Low = ParameterData['PsiE2_Low','value'],
		PsiE2_Mid = ParameterData['PsiE2_Mid','value'],		
		PsiE2_High = ParameterData['PsiE2_High','value'],
		Gamma = ParameterData['Gamma','value'],
		RefCO2Conc = InitialData['CO2Conc','value'],
		OtherRadForce = ParameterData['OtherRadForce','value'],

    # Economy Coefficients
		CoalCapitalReturn_Low = ParameterData['CoalCapitalReturn_Low','value'],
		CoalCapitalReturn_Mid = ParameterData['CoalCapitalReturn_Mid','value'],
		CoalCapitalReturn_High = ParameterData['CoalCapitalReturn_High','value'],
		OilCapitalReturn_Low = ParameterData['OilCapitalReturn_Low','value'],
		OilCapitalReturn_Mid = ParameterData['OilCapitalReturn_Mid','value'],
		OilCapitalReturn_High = ParameterData['OilCapitalReturn_High','value'],
		GasCapitalReturn_Low = ParameterData['GasCapitalReturn_Low','value'],
		GasCapitalReturn_Mid = ParameterData['GasCapitalReturn_Mid','value'],
		GasCapitalReturn_High = ParameterData['GasCapitalReturn_High','value'],
		CapitalInputElast_Low = ParameterData['CapitalInputElast_Low','value'],
		CapitalInputElast_Mid = ParameterData['CapitalInputElast_Mid','value'],
		CapitalInputElast_High = ParameterData['CapitalInputElast_High','value'],
		LaborInputElast_Low = ParameterData['LaborInputElast_Low','value'],
		LaborInputElast_Mid = ParameterData['LaborInputElast_Mid','value'],
		LaborInputElast_High = ParameterData['LaborInputElast_High','value'],
		TechMult_Low = ParameterData['TechMult_Low','value'],
		TechMult_Mid = ParameterData['TechMult_Mid','value'],
		TechMult_High = ParameterData['TechMult_High','value'],
		CoalAccess_Low = ParameterData['CoalAccess_Low','value'],
		CoalAccess_Mid = ParameterData['CoalAccess_Mid','value'],
		CoalAccess_High = ParameterData['CoalAccess_High','value'],
		OilAccess_Low = ParameterData['OilAccess_Low','value'],
		OilAccess_Mid = ParameterData['OilAccess_Mid','value'],
		OilAccess_High = ParameterData['OilAccess_High','value'],
		GasAccess_Low = ParameterData['GasAccess_Low','value'],
		GasAccess_Mid = ParameterData['GasAccess_Mid','value'],
		GasAccess_High = ParameterData['GasAccess_High','value'],
		LowEmployedWorkRatio_M1 = ParameterData['LowEmployedWorkRatio_M1','value'], 
		LowEmployedWorkRatio_M2 = ParameterData['LowEmployedWorkRatio_M2','value'], 
		LowEmployedWorkRatio_M3 = ParameterData['LowEmployedWorkRatio_M3','value'], 
		LowEmployedWorkRatio_M4 = ParameterData['LowEmployedWorkRatio_M4','value'], 
		LowEmployedWorkRatio_F1 = ParameterData['LowEmployedWorkRatio_F1','value'], 
		LowEmployedWorkRatio_F2 = ParameterData['LowEmployedWorkRatio_F2','value'], 
		LowEmployedWorkRatio_F3 = ParameterData['LowEmployedWorkRatio_F3','value'], 
		LowEmployedWorkRatio_F4 = ParameterData['LowEmployedWorkRatio_F4','value'],            
		MidEmployedWorkRatio_M1 = ParameterData['MidEmployedWorkRatio_M1','value'], 
		MidEmployedWorkRatio_M2 = ParameterData['MidEmployedWorkRatio_M2','value'], 
		MidEmployedWorkRatio_M3 = ParameterData['MidEmployedWorkRatio_M3','value'], 
		MidEmployedWorkRatio_M4 = ParameterData['MidEmployedWorkRatio_M4','value'], 
		MidEmployedWorkRatio_F1 = ParameterData['MidEmployedWorkRatio_F1','value'], 
		MidEmployedWorkRatio_F2 = ParameterData['MidEmployedWorkRatio_F2','value'], 
		MidEmployedWorkRatio_F3 = ParameterData['MidEmployedWorkRatio_F3','value'], 
		MidEmployedWorkRatio_F4 = ParameterData['MidEmployedWorkRatio_F4','value'],            
		HighEmployedWorkRatio_M1 = ParameterData['HighEmployedWorkRatio_M1','value'], 
		HighEmployedWorkRatio_M2 = ParameterData['HighEmployedWorkRatio_M2','value'], 
		HighEmployedWorkRatio_M3 = ParameterData['HighEmployedWorkRatio_M3','value'], 
		HighEmployedWorkRatio_M4 = ParameterData['HighEmployedWorkRatio_M4','value'], 
		HighEmployedWorkRatio_F1 = ParameterData['HighEmployedWorkRatio_F1','value'], 
		HighEmployedWorkRatio_F2 = ParameterData['HighEmployedWorkRatio_F2','value'], 
		HighEmployedWorkRatio_F3 = ParameterData['HighEmployedWorkRatio_F3','value'], 
		HighEmployedWorkRatio_F4 = ParameterData['HighEmployedWorkRatio_F4','value'],            
		SavingsRate_Low = ParameterData['SavingsRate_Low','value'],
		SavingsRate_Mid = ParameterData['SavingsRate_Mid','value'],
		SavingsRate_High = ParameterData['SavingsRate_High','value'],
		DeprecRate_Low = ParameterData['DeprecRate_Low','value'],
		DeprecRate_Mid = ParameterData['DeprecRate_Mid','value'],
		DeprecRate_High = ParameterData['DeprecRate_High','value'],
		IneqMult_Low = ParameterData['IneqMult_Low','value'],
		IneqMult_Mid = ParameterData['IneqMult_Mid','value'],
		IneqMult_High = ParameterData['IneqMult_High','value'],
		InitEconOutputGrowth_Low = ParameterData['InitEconOutputGrowth_Low','value'],
		InitEconOutputGrowth_Mid = ParameterData['InitEconOutputGrowth_Mid','value'],
		InitEconOutputGrowth_High = ParameterData['InitEconOutputGrowth_High','value'],

	# Resource Coefficients	
		CoalConsIntensity_Low = ParameterData['CoalConsIntensity_Low','value'],
		CoalConsIntensity_Mid = ParameterData['CoalConsIntensity_Mid','value'],
		CoalConsIntensity_High = ParameterData['CoalConsIntensity_High','value'],
		OilConsIntensity_Low = ParameterData['OilConsIntensity_Low','value'],		
		OilConsIntensity_Mid = ParameterData['OilConsIntensity_Mid','value'],
		OilConsIntensity_High = ParameterData['OilConsIntensity_High','value'],
		GasConsIntensity_Low = ParameterData['GasConsIntensity_Low','value'],		
		GasConsIntensity_Mid = ParameterData['GasConsIntensity_Mid','value'],
		GasConsIntensity_High = ParameterData['GasConsIntensity_High','value'],

    # Water Coefficients
		DeltaW = ParameterData['DeltaW','value'],
		WaterReplMax = ParameterData['WaterReplMax','value'],
		ZetaI1_Low = ParameterData['ZetaI1_Low','value'],
		ZetaI1_Mid = ParameterData['ZetaI1_Mid','value'],
		ZetaI1_High = ParameterData['ZetaI1_High','value'],
		ZetaI2_Low = ParameterData['ZetaI2_Low','value'],
		ZetaI2_Mid = ParameterData['ZetaI2_Mid','value'],
		ZetaI2_High = ParameterData['ZetaI2_High','value'],
		WaterDemandPC_Low = ParameterData['WaterDemandPC_Low','value'],
		WaterDemandPC_Mid = ParameterData['WaterDemandPC_Mid','value'],
		WaterDemandPC_High = ParameterData['WaterDemandPC_High','value'],

    # Health and Education Coefficients
		ZetaE_Low = ParameterData['ZetaE_Low','value'],
		ZetaE_Mid = ParameterData['ZetaE_Mid','value'],
		ZetaE_High = ParameterData['ZetaE_High','value'],
		ZetaH_Low = ParameterData['ZetaH_Low','value'],
		ZetaH_Mid = ParameterData['ZetaH_Mid','value'],
		ZetaH_High = ParameterData['ZetaH_High','value'],
		LambdaE_Low = ParameterData['LambdaE_Low','value'],
		LambdaE_Mid = ParameterData['LambdaE_Mid','value'],
		LambdaE_High = ParameterData['LambdaE_High','value'],
		LambdaH_Low = ParameterData['LambdaH_Low','value'],
		LambdaH_Mid = ParameterData['LambdaH_Mid','value'],
		LambdaH_High = ParameterData['LambdaH_High','value'],
		ChiEF1_Low = ParameterData['ChiEF1_Low','value'],
		ChiEF1_Mid = ParameterData['ChiEF1_Mid','value'],
		ChiEF1_High = ParameterData['ChiEF1_High','value'], 
		ChiHF1_Low = ParameterData['ChiHF1_Low','value'],
		ChiHF1_Mid = ParameterData['ChiHF1_Mid','value'],
		ChiHF1_High = ParameterData['ChiHF1_High','value'], 
		ChiHA1_RichLow = ParameterData['ChiHA1_RichLow','value'],
		ChiHA1_RichMid = ParameterData['ChiHA1_RichMid','value'],
		ChiHA1_RichHigh = ParameterData['ChiHA1_RichHigh','value'], 
		ChiHA1_PoorLow = ParameterData['ChiHA1_PoorLow','value'],
		ChiHA1_PoorMid = ParameterData['ChiHA1_PoorMid','value'],
		ChiHA1_PoorHigh = ParameterData['ChiHA1_PoorHigh','value'],
		ChiEF2_Low = ParameterData['ChiEF2_Low','value'],
		ChiEF2_Mid = ParameterData['ChiEF2_Mid','value'],
		ChiEF2_High = ParameterData['ChiEF2_High','value'], 
		ChiHF2_Low = ParameterData['ChiHF2_Low','value'],
		ChiHF2_Mid = ParameterData['ChiHF2_Mid','value'],
		ChiHF2_High = ParameterData['ChiHF2_High','value'], 
		ChiHA2_RichLow = ParameterData['ChiHA2_RichLow','value'],
		ChiHA2_RichMid = ParameterData['ChiHA2_RichMid','value'],
		ChiHA2_RichHigh = ParameterData['ChiHA2_RichHigh','value'], 
		ChiHA2_PoorLow = ParameterData['ChiHA2_PoorLow','value'],
		ChiHA2_PoorMid = ParameterData['ChiHA2_PoorMid','value'],
		ChiHA2_PoorHigh = ParameterData['ChiHA2_PoorHigh','value'],
		ChiHA3_RichLow = ParameterData['ChiHA3_RichLow','value'],
		ChiHA3_RichMid = ParameterData['ChiHA3_RichMid','value'],
		ChiHA3_RichHigh = ParameterData['ChiHA3_RichHigh','value'], 
		ChiHA3_PoorLow = ParameterData['ChiHA3_PoorLow','value'],
		ChiHA3_PoorMid = ParameterData['ChiHA3_PoorMid','value'],
		ChiHA3_PoorHigh = ParameterData['ChiHA3_PoorHigh','value'])

# Process Calibration Data

yobs = na.omit(melt(CalibData,id='time'))
yobs$variable = as.character(yobs$variable)
yobs = yobs[,c('variable','time','value')]

